version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/entrypoint.sh  
    image: neerajtiwari0007/composertest:0.1
    init: true
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "8000:8000"  
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: none

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]  

