services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
    - sleep
    - infinity
    image: neerajtiwari0007/composertest:0.1
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

